### ISSUE TITLE
Add thermostat control

### ISSUE THREAD

**Issue by JQE** [k3vmcd/ha-micro-air-easytouch#16]
Is it possible to add the ability to change the thermostat mode? I have a solar setup with my camper, sometimes when I have guests or if my kids aren't thinking people turn on my ac or fans and drain my batteries. I want to use this with my victron shunt so if my batteries are below 75% it shuts off the ac and fans to protect our charge. 

I do program a bit, so I could dig in but it looks like you have a solid understanding of this so I was hoping it's something you could add, or toss a quick explanation on how / if it can be added or where I can start.

**Comment by JQE** [comment]
Also wanted to add this worked perfectly and I love it so far. Thanks!

**Comment by k3vmcd** [comment]
@JQE try the [v0.2.0-alpha-2](https://github.com/k3vmcd/ha-micro-air-easytouch/releases/tag/v0.2.0-alpha-2) release. I've added the controls, but it has several bugs in it still so I've not made it the main release yet.

 I released it in a way that you could still use HACS, but it won't automatically select it in HACS. You have to "update information" -> "redownload" -> and then select the v0.2.0-alpha-2 as the release you want to download on this screen. Please make sure to delete your existing device before you download/restart Home Assistant so it starts fresh.

![Image](https://github.com/user-attachments/assets/095108b4-d0a1-4a70-90c0-1ff704529bdc)

**Comment by JQE** [comment]
Will try for sure. Thinking I might need to setup the bt proxy as I seem to have lost connection. Was working fine for a bit.

**Comment by phurth** [comment]
I'm using a BT proxy and get disconnects. I think it's one of the aforementioned bugs remaining to be squashed. Still, tremendous progress here on this project.

**Comment by JQE** [comment]
Seems to be working perfectly now. Thanks!

**Comment by k3vmcd** [comment]
[v0.2.0](https://github.com/k3vmcd/ha-micro-air-easytouch/releases/tag/v0.2.0) released with thermostat control
